# .github/workflows/deploy.yml
name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # or master, depending on your default branch
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if any)
      run: npm test --if-present
      
    - name: Create deployment package
      run: |
        # Create a deployment directory
        mkdir -p deployment
        
        # Copy necessary files (exclude node_modules, .git, etc.)
        cp app.js deployment/
        cp package.json deployment/
        cp package-lock.json deployment/
        
        # Create zip file with timestamp
        cd deployment
        zip -r ../week3-app-$(date +%Y%m%d-%H%M%S).zip .
        cd ..
        
        # Set the zip file name as environment variable for later steps
        echo "ZIP_FILE=$(ls week3-app-*.zip)" >> $GITHUB_ENV
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Upload to S3
      run: |
        # Upload zip file to S3 bucket
        aws s3 cp $ZIP_FILE s3://${{ secrets.S3_BUCKET_NAME }}/deployments/$ZIP_FILE
        
        # Set S3 object key for Elastic Beanstalk deployment
        echo "S3_OBJECT_KEY=deployments/$ZIP_FILE" >> $GITHUB_ENV
        
    - name: Deploy to Elastic Beanstalk
      run: |
        # Create new application version
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APPLICATION_NAME }} \
          --version-label ${{ github.sha }}-$(date +%Y%m%d-%H%M%S) \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=$S3_OBJECT_KEY \
          --description "Deployed from GitHub Actions - Commit: ${{ github.sha }}"
          
        # Update environment with new version
        aws elasticbeanstalk update-environment \
          --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
          --version-label ${{ github.sha }}-$(date +%Y%m%d-%H%M%S)
          
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to complete..."
        aws elasticbeanstalk wait environment-updated \
          --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }}
          
    - name: Get deployment status
      run: |
        aws elasticbeanstalk describe-environments \
          --environment-names ${{ secrets.EB_ENVIRONMENT_NAME }} \
          --query 'Environments[0].[EnvironmentName,Status,Health]' \
          --output table